services:

  # =========== DMZ / Public Subnet ===========

  reverse-proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - public
      - private
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  db-admin:
    image: adminer:latest
    networks:
      - private

  bank:
    build: ./mock-bank
    container_name: mock_bank
    environment:
      API_KEY: PROCESSOR-BANK-SECRET
    volumes:
      - ./mock-bank/app:/app
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - public

  webhook-sink:
    build: ./webhook-sink
    container_name: webhook-sink
    volumes:
      - ./webhook-sink/app:/app
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - public

  # =========== Private Subnet ===========

  db:
    image: postgres:16
    container_name: pay_db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway_user -d payments"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - private

  message-broker:
    image: rabbitmq:alpine
    container_name: pay_message_broker
    environment: 
      RABBITMQ_DEFAULT_USER: pay_user
      RABBITMQ_DEFAULT_PASS: pay_password
    networks:
        - private
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  gateway:
    build: ./gateway
    container_name: pay_gateway
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: payments
      DB_USER: gateway_user
      DB_PASSWORD: gateway_pass
      MQ_HOST: message-broker
      MQ_PORT: 5672
      MQ_USER: pay_user
      MQ_PASSWORD: pay_password
    volumes:
      - ./gateway/app:/app
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - private

  processor:
    build: ./processor
    container_name: pay_processor
    environment:
      PYTHONUNBUFFERED: "1"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: payments
      DB_USER: processor_user
      DB_PASSWORD: processor_pass
      BANK_HOST: reverse-proxy/bank
      BANK_PORT: 8000
      BANK_AUTH: PROCESSOR-BANK-SECRET
      MQ_HOST: message-broker
      MQ_PORT: 5672
      MQ_USER: pay_user
      MQ_PASSWORD: pay_password
    volumes:
      - ./processor/app:/app
      - ./logs:/app/logs
    command: python main.py
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - private

  notification-service:
    build: ./notification-service
    container_name: pay_notification_service
    environment:
      PYTHONUNBUFFERED: "1"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: payments
      DB_USER: processor_user
      DB_PASSWORD: processor_pass
      MQ_HOST: message-broker
      MQ_PORT: 5672
      MQ_USER: pay_user
      MQ_PASSWORD: pay_password
    volumes:
      - ./notification-service/app:/app
    command: python main.py
    depends_on:
      db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - private

volumes:
  pgdata:

networks:
  public:
    driver: bridge

  private:
    internal: true
    driver: bridge